### ISSUE TITLE
Fix: interpolation onto PoE

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/toshi-hazard-haste#3]
We want interpolation of the hazard onto a desired PoE to be robust against numerical "quirks" in the hazard curve.

Interpolation of the hazard curve onto a desired probability of exceedence (PoE) assumes that the hazard probability curve monotonically decreases as shaking level (acceleration) increases. However there are two identified ways in which this may not be true:
- at very high probability (low shaking level) numerical precision can cause the probability to increase with shaking level. This has been observed to occur over the first two shaking levels
- at very high shaking levels the probability is `0` and does not decrease further as shaking level increases

Done when: 
- [x] small increases in probability at low shaking does not cause a problem
- [x] curves with `0` probability at high levels of shaking do not cause a problem
- [x] other cases of the hazard curve not monotonically decreasing with shaking level are logged as warning for manual inspection

**Comment by chrisdicaprio** [comment]
Eample of case 1:
for model ID `SLT_v8_gmm_v2_FINAL` increasing prob at vs30=400, imt=PGA, loc=(-40.0, 175.2), agg=0.9
```
shaking levels levels: [0.0001, 0.0002, 0.0004, 0.0006, 0.0008, 0.001, 0.002, 0.004, 0.006, 0.008, 0.01, 0.02, 0.04, 0.06, 0.08, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0, 3.5, 4.0, 4.5, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
probability: [6.38968165e-01 6.38984832e-01 6.38924165e-01 6.38617806e-01
 6.37731501e-01 6.36442448e-01 6.20736015e-01 5.74451729e-01
 5.26512111e-01 4.81553216e-01 4.41798316e-01 3.04196861e-01
 1.75138679e-01 1.16094023e-01 8.31429645e-02 6.26495176e-02
 2.27536245e-02 1.14596619e-02 6.72560090e-03 4.30892990e-03
 2.92385190e-03 2.07031900e-03 1.51920210e-03 1.14742690e-03
 8.85213900e-04 5.66035800e-04 3.75791900e-04 2.45817400e-04
 1.65475200e-04 1.14433100e-04 8.09856000e-05 5.83670000e-05
 4.27613000e-05 3.17869000e-05 2.39675000e-05 1.21926000e-05
 6.62650000e-06 3.72450000e-06 2.15000000e-06 7.58300000e-07
 3.16000000e-07 1.51300000e-07 7.73000000e-08 4.06000000e-08]
```

**Comment by chrisdicaprio** [comment]
Example of case 2 (`SLT_v8_gmm_v2_FINAL`)
```
increasing prob at 400, PGA, (-46.3, 167.4), 0.025
levels: [0.0001, 0.0002, 0.0004, 0.0006, 0.0008, 0.001, 0.002, 0.004, 0.006, 0.008, 0.01, 0.02, 0.04, 0.06, 0.08, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0, 3.5, 4.0, 4.5, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
values: [3.19377240e-01 3.19376911e-01 3.19352911e-01 3.18859070e-01
 3.16647243e-01 3.12706010e-01 2.80898894e-01 2.41411558e-01
 1.93387035e-01 1.58890034e-01 1.34048791e-01 7.21953604e-02
 3.35497604e-02 1.99410510e-02 1.32755955e-02 9.36776000e-03
 2.46211800e-03 9.04242900e-04 4.08742000e-04 2.08512000e-04
 1.14830400e-04 6.61910000e-05 3.95460000e-05 2.46083000e-05
 1.58572000e-05 6.97740000e-06 3.26310000e-06 1.53580000e-06
 7.48900000e-07 3.68100000e-07 1.85600000e-07 9.15000000e-08
 4.72000000e-08 2.49000000e-08 1.13000000e-08 2.20000000e-09
 3.00000000e-10 1.00000000e-10 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
```

**Comment by chrisdicaprio** [comment]
magic numbers:
- ignore values below `1e-10`
- ignore values above `0.632`

**Comment by voj** [comment]
merged
